language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - 39.96.181.105
before_install:
- openssl aes-256-cbc -K $encrypted_f952ec1043d3_key -iv $encrypted_f952ec1043d3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@39.96.181.105 -o StrictHostKeyChecking=no 'cd ~/aliyun_travis  && git pull && npm install && npm run build'
